In [1]:
import torch

In [34]:
t = torch.Tensor([1, 2, 3, 2, 5, 8, 2, 1, 2, 3, 2, 5, 8, 2, 1, 2, 3, 2, 5, 8, 2])
idx = (t==2).nonzero(as_tuple=True)[0]
p = 0.8
idx2 = torch.randperm(idx.size(0))[:int(idx.size(0)*p)]

print(idx)
print(idx2)

# t = idx[idx2] += 1000.
print(t)
#(t == 1).nonzero(as_tuple=True)[0]

# print(idx)
# print(dd)


# x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0])
# p = 0.2
# idx = torch.randperm(x.size(0))[:int(x.size(0)*p)]
# x[idx] += 10.
# print(idx, x)

tensor([ 1,  3,  6,  8, 10, 13, 15, 17, 20])
tensor([3, 2, 1, 0, 7, 5, 4])
tensor([1., 2., 3., 2., 5., 8., 2., 1., 2., 3., 2., 5., 8., 2., 1., 2., 3., 2.,
        5., 8., 2.])


In [8]:
a = torch.rand(2,6,4)

In [11]:
b = torch.tensor([[0,1,2],[1,2,3]])

In [14]:
a

tensor([[[0.8147, 0.8236, 0.8627, 0.1525],
         [0.6685, 0.5481, 0.0221, 0.5344],
         [0.9117, 0.5772, 0.5216, 0.5589],
         [0.5426, 0.0492, 0.4549, 0.4488],
         [0.7154, 0.0356, 0.3257, 0.8024],
         [0.3679, 0.4271, 0.8270, 0.5147]],

        [[0.0908, 0.9541, 0.1238, 0.1288],
         [0.3720, 0.0257, 0.2582, 0.9554],
         [0.4001, 0.7001, 0.7651, 0.8985],
         [0.0635, 0.6687, 0.6294, 0.0050],
         [0.2122, 0.3229, 0.9145, 0.6928],
         [0.6203, 0.2038, 0.6570, 0.5542]]])

In [16]:
a[:, b, :]

tensor([[[[0.8147, 0.8236, 0.8627, 0.1525],
          [0.6685, 0.5481, 0.0221, 0.5344],
          [0.9117, 0.5772, 0.5216, 0.5589]],

         [[0.6685, 0.5481, 0.0221, 0.5344],
          [0.9117, 0.5772, 0.5216, 0.5589],
          [0.5426, 0.0492, 0.4549, 0.4488]]],


        [[[0.0908, 0.9541, 0.1238, 0.1288],
          [0.3720, 0.0257, 0.2582, 0.9554],
          [0.4001, 0.7001, 0.7651, 0.8985]],

         [[0.3720, 0.0257, 0.2582, 0.9554],
          [0.4001, 0.7001, 0.7651, 0.8985],
          [0.0635, 0.6687, 0.6294, 0.0050]]]])